### ISSUE TITLE
1.19.4净化之种，种植在地狱岩报错 bs重构版sf

### ISSUE THREAD

**Issue by uouiiu** [SlimefunGuguProject/Netheopoiesis#15]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Netheopoiesis/issues)，且没有找到相同的问题

### 问题描述

Error Generated: 2023-05-15-13-55

Java Environment:
  Operating System: Windows 10
  Java Version: 17.0.4.1

Server Software: Purpur
  Build: git-Purpur-1969 (MC: 1.19.4)
  Minecraft v1.19.4-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun v7b6fdc3-canary
  Caused by: Netheopoiesis vBuild 10 zh-CN(SlimefunGuguProject) (git 7fa7e71)

Installed Addons (13)
  + CMILib 1.2.5.3
  + GuizhanLibPlugin Build 22 (git 2f447db)
  + CMI 9.5.0.8
  + Wildernether Build 4 zh-CN(SlimefunGuguProject) (git 32218bd)
  + SpiritsUnchained Build 5 zh-CN(SlimefunGuguProject) (git f64a11b)
  + SlimefunItemExpansion 1.0.2
  + SlimefunAdvancements Build 11 zh-CN(ybw0014) (git 446b8ba)
  + Netheopoiesis Build 10 zh-CN(SlimefunGuguProject) (git 7fa7e71)
  + Gastronomicon Build 4 zh-CN(SlimefunGuguProject) (git ba22ed8)
  + FluffyMachines Build 17 zh-CN(baoad) (git 1982d30)
  + Endrex Build 1 zh-CN(SlimefunGuguProject) (git 23dbf5e)
  + DemonicExpansion Build 1 zh-CN(SlimefunGuguProject) (git 67dfc39)
  + Cultivation DEV - 9 (git df727409)

Installed Plugins (51):
  + ViaVersion 4.6.2
  + LuckPerms 5.4.40
  + ProtocolLib 5.0.0
  + Vault 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
  + PlaceholderAPI 2.11.3
  + Citizens 2.0.31-SNAPSHOT (build 3011)
  + BentoBox 1.23.1
  + WorldEdit 7.2.14+6360-094b734
  + Multiverse-Core 4.3.1-b861
  + Slimefun 7b6fdc3-canary
  + eco 6.57.2
  + CMILib 1.2.5.3
  + GuizhanLibPlugin Build 22 (git 2f447db)
  + ViaBackwards 4.6.1
  + EcoEnchants 10.10.0
  + CMI 9.5.0.8
  + spark 1.10.38
  + VoidWorld 1.0
  + LaggRemover 2.0.6
  + LuckTextures 1.2
  + Wildernether Build 4 zh-CN(SlimefunGuguProject) (git 32218bd)
  + ViaRewind 2.0.2
  + TrChat 2.0.0-PRE-38
  + SpiritsUnchained Build 5 zh-CN(SlimefunGuguProject) (git f64a11b)
  + SlimefunItemExpansion 1.0.2
  + SlimefunAdvancements Build 11 zh-CN(ybw0014) (git 446b8ba)
  + ReallyFakePlayers 1.12.0-BETA
  + PlayerTop 1.2.6
  + Netheopoiesis Build 10 zh-CN(SlimefunGuguProject) (git 7fa7e71)
  + LiteSignIn 1.7.0.0
  + Invero 1.0.6
  + ILoreEdit 2.5.1
  + Gastronomicon Build 4 zh-CN(SlimefunGuguProject) (git ba22ed8)
  + FluffyMachines Build 17 zh-CN(baoad) (git 1982d30)
  - FakePlayers 2.7
  + Endrex Build 1 zh-CN(SlimefunGuguProject) (git 23dbf5e)
  + DemonicExpansion Build 1 zh-CN(SlimefunGuguProject) (git 67dfc39)
  + DeluxeMenus 1.13.7-Release
  + DecentHolograms 2.8.1
  + CustomCobbleGen 1.5.0
  + Cultivation DEV - 9 (git df727409)
  + AnimatedScoreboard 0.2.7
  + libreforge 4.10.0
  + BentoBox-Bank 1.5.0
  + BentoBox-Biomes 2.1.1
  + BentoBox-BSkyBlock 1.16.1
  + BentoBox-Challenges 1.2.0
  + BentoBox-Level 2.10.0
  + BentoBox-Likes 2.3.1
  + BentoBox-Visit 1.6.0
  + BentoBox-Warps 1.13.0

Block Info:
  World: bskyblock_world_nether
  X: -4
  Y: 85
  Z: 1598
  Material: PLAYER_HEAD
  Block Data: org.bukkit.craftbukkit.v1_19_R3.block.impl.CraftSkullPlayer
  State: org.bukkit.craftbukkit.v1_19_R3.block.CraftSkull

Ticker-Info:
  Type: Synchronized

Slimefun Data:
  ID: NPS_PURIFICATION_SEED
  Is data loaded: true
  Inventory: true
  Data: 

Stacktrace:

java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at Netheopoiesis-Build 10 zh-CN(SlimefunGuguProject) (git 7fa7e71) (3).jar//dev.sefiraat.netheopoiesis.api.items.NetherSeed.onTick(NetherSeed.java:157)
	at Netheopoiesis-Build 10 zh-CN(SlimefunGuguProject) (git 7fa7e71) (3).jar//dev.sefiraat.netheopoiesis.api.items.NetherSeed$1.tick(NetherSeed.java:130)
	at Slimefun-v263c5ab-canary.jar//me.mrCookieSlime.Slimefun.Objects.handlers.BlockTicker.tick(BlockTicker.java:59)
	at Slimefun-v263c5ab-canary.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:169)
	at Slimefun-v263c5ab-canary.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickLocation$2(TickerTask.java:150)
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1510)
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1195)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
	at java.base/java.lang.Thread.run(Thread.java:833)
这个是error-reports中的日志

[13:59:04 WARN]: [Netheopoiesis]
[13:59:04 WARN]: [Netheopoiesis] An Error occurred! It has been saved as:
[13:59:04 WARN]: [Netheopoiesis] /plugins/Slimefun/error-reports/2023-05-15-13-59.err
[13:59:04 WARN]: [Netheopoiesis] Please put this file on https://pastebin.com/ and report this to the developer(s).
[13:59:04 WARN]: [Netheopoiesis] Bug Tracker: https://github.com/SlimefunGuguProject/Netheopoiesis/issues/
[13:59:04 WARN]: [Netheopoiesis]
[13:59:06 ERROR]: [Slimefun] X: -4 Y: 85 Z: 1,598 (NPS_PURIFICATION_SEED)
[13:59:06 ERROR]: [Slimefun] has thrown 4 error messages in the last 4 Ticks, the Block has been terminated.
[13:59:06 ERROR]: [Slimefun] Check your /plugins/Slimefun/error-reports/ folder for details.
[13:59:06 ERROR]: [Slimefun]
这个是后台黑框当时的报错

### 复现步骤

在地狱，地狱岩种植净化种子
过2-3秒，种子消失，然后就出现这个报错

### 预期行为

我不到啊，原配置没动过

### 服务器日志

(不会上传，发在问题描述中了)

### 错误报告

(不会上传，发在问题描述中了)

### 服务端软件

Purpur

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Slimefun-v263c5ab-canary

### 插件版本

Build 10 zh-CN(SlimefunGuguProject) (git 7fa7e71)

**Comment by ybw0014** [comment]
看上去是方块数据丢失了，可能需要对新版bs适配一下

**Comment by uouiiu** [comment]
什么时候能才能修复它

**Comment by ybw0014** [comment]
请在Q群内下载修复版本协助测试

**Comment by uouiiu** [comment]
群号是什么

> 请在Q群内下载修复版本协助测试

**Comment by ybw0014** [comment]
> 群号是什么
> 
> > 请在Q群内下载修复版本协助测试

汉化组[主页](https://github.com/SlimefunGuguProject)以及[新建issue页面](https://github.com/SlimefunGuguProject/Netheopoiesis/issues/new/choose)都可以找到。
